### ISSUE TITLE
actividad11-destello-movil 

### ISSUE THREAD

**Issue by carlos0716c** [SistemasTecTlaxiaco/actividad-11-destello-movil#1]
[practica11.pdf](https://github.com/user-attachments/files/18101602/practica11.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado..

**Comment by ka194** [comment]
Portada y escudos institucionales: 25 puntos
Incluye objetivos: 25 puntos
Tiene descripción clara: 25 puntos
Contiene resultados y conclusión: 25 puntos
Porcentaje obtenido 100% = 50 puntos
